FROM maven:3.9-eclipse-temurin-21
WORKDIR /app

COPY pom.xml .
RUN mvn dependency:go-offline

COPY src ./src

ENV SPRING_PROFILES_ACTIVE=dev
ENV JAVA_TOOL_OPTIONS="-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005"

EXPOSE 8080 5005
CMD ["mvn", "spring-boot:run", "-Dspring-boot.run.jvmArguments=-Dlogging.level.root=DEBUG"]
