apiVersion: v1
kind: ConfigMap
metadata:
  name: fluent-bit-config
data:
  fluent-bit.conf: |
    [SERVICE]
        Flush        1
        Daemon       Off
        Log_Level    info

    [INPUT]
        Name         tail
        Path         /var/log/app/*.log
        Tag          app.backend
        Refresh_Interval 1

    [OUTPUT]
        Name         stdout
        Match        *
