apiVersion: v1
kind: Secret
metadata:
  name: trackorder-secret
type: Opaque
stringData:
  DB_PASSWORD: "change-me"
  JWT_SECRET: "change-me-with-long-random-secret-min-64-chars"
  STRIPE_SECRET_KEY: "sk_test_change_me"
  STRIPE_WEBHOOK_SECRET: "whsec_change_me"
