apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: trackorder-prod

resources:
  - ../../base

patches:
  - path: patch-backend.yaml
  - path: patch-frontend.yaml
  - path: patch-postgres.yaml
  - path: patch-service-frontend.yaml

images:
  - name: trackorder-backend:prod
    newName: gcr.io/gestion-de-livraison-493711/backend
    newTag: prod
  - name: trackorder-frontend:prod
    newName: gcr.io/gestion-de-livraison-493711/frontend
    newTag: prod
