apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: trackorder-frontend
  template:
    metadata:
      labels:
        app: trackorder-frontend
    spec:
      containers:
      - name: trackorder-frontend
        image: trackorder-frontend:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
